name: Garage CI

env:
  GARAGE_GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
  PR_COMMIT_RANGE: origin/${{ github.base_ref }}...origin/${{ github.head_ref }}
  DOCKER_TAG: garage-ci-${{ github.run_id }}
  OWNER: "rlworkgroup"
  DOCKER_CACHE_REPO: "garage-ci"
  MJKEY: ${{ secrets.MJKEY }}
  CI_USER: rlworkgroupbot
  IS_PR_FROM_FORK: ${{ github.event.client_payload.pull_request.head.repo.fork }}

on:
  push:
    branches:
      - master
    # Triggers on release candidates from master
    tags:
      - 'v[1-9][0-9]*.[0-9]+.[0-9]+rc[0-9]'
      - 'v2020.06.[0-9]+rc[0-9]'
  pull_request:
    branches:
      - master
      - 'release-.*'
  repository_dispatch:
    types: [ ok-to-test-command ]

jobs:
  comment_link_to_output_on_fork_pr:
    name: Post link to CI output for fork PRs
    runs-on: ubuntu-latest
    # can't use env.IS_PR_FROM_FORK here because env is not available here
    if: github.event.client_payload.pull_request.head.repo.fork
    steps:
      - name: Dump the client payload context
        env:
          PAYLOAD_CONTEXT: ${{ toJson(github.event.client_payload) }}
        run: echo "$PAYLOAD_CONTEXT"
      - name: Create URL to the run output
        id: vars
        run: echo ::set-output name=run-url::https://github.com/$GITHUB_REPOSITORY/actions/runs/$GITHUB_RUN_ID

      - name: Create comment
        uses: peter-evans/create-or-update-comment@v1
        with:
          token: ${{ secrets.CI_REGISTRY_TOKEN }}
          repository: ${{ github.event.client_payload.github.payload.repository.full_name }}
          issue-number: ${{ github.event.client_payload.github.payload.issue.number }}
          body: |
            [Command run output][1] for ${{ github.event.client_payload.pull_request.html_url }}/commits/${{ github.event.client_payload.pull_request.head.sha }}

            [1]: ${{ steps.vars.outputs.run-url }}
      - name: Get Check runs
        id: check-runs
        run: |
          checks=$(curl -H 'Accept: application/vnd.github.v3+json' \
                           https://api.github.com/repos/gitanshu/garage/commits/730a0d1/check-suites \
                           | jq '.check_suites[-1].check_runs_url' \
                           | xargs curl -H 'Accept: application/vnd.github.v3+json' \
                           | jq -c .)
          echo "checks=$checks" >> $GITHUB_ENV


  build_docker_container:
    name: Build Docker Container
    runs-on: ubuntu-latest
    needs: comment_link_to_output_on_fork_pr
    if: ${{ always() && !(github.event.pull_request.head.repo.fork && github.event_name == 'pull_request') }}
    steps:
      - run: echo $checks
      - name: Docker info
        run: docker version
      - uses: actions/checkout@v2
        if: !env.IS_PR_FROM_FORK
        with:
          fetch-depth: 0
      - uses: actions/checkout@v2
        if: env.IS_PR_FROM_FORK
        with:
          ref: ${{ github.event.client_payload.pull_request.merge_commit_sha }}
          fetch-depth: 0
      - name: Login to GitHub Package Registry
        run: echo ${{ secrets.CI_REGISTRY_TOKEN }} | docker login docker.pkg.github.com -u ${CI_USER} --password-stdin
      - name: Build Docker container
        run: |
          DOCKER_BUILDKIT=1 docker build . \
            -f docker/Dockerfile \
            --target garage-dev \
            -t "${DOCKER_TAG}" \
            --build-arg GARAGE_GH_TOKEN \
            --cache-from="rlworkgroup/garage"
      - name: Push to cache (GitHub Package Registry)
        run: |
          docker tag "${DOCKER_TAG}" "docker.pkg.github.com/${OWNER}/${DOCKER_CACHE_REPO}/${DOCKER_TAG}"
          docker push "docker.pkg.github.com/${OWNER}/${DOCKER_CACHE_REPO}/${DOCKER_TAG}"
      - name: Get Check Id
        if: always() && env.IS_PR_FROM_FORK
        id: check
        run: |
          check_id=$(echo $checks | jq -c '.check_runs[] | select(.name | contains("Build Docker Container") | .id)')
          echo "::set-output name=id::$check_id"
      - run: echo "${{ steps.check.outputs.id }}"
      - name: Update check status for PRs from forks
        uses: LouisBrunner/checks-action@v1.1.1
        if: always() && env.IS_PR_FROM_FORK
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          check_id: ${{ steps.check.outputs.id }}
          sha: ${{ github.event.client_payload.pull_request.head.sha }}
          conclusion: ${{ job.status }}


  check_pre_commit:
    name: Check pre-commit
    runs-on: ubuntu-latest
    needs: build_docker_container

    steps:
    - name: Login to GitHub Package Registry
      if: github.event_name == 'pull_request' || env.IS_PR_FROM_FORK
      run: echo ${{ secrets.CI_REGISTRY_TOKEN }} | docker login docker.pkg.github.com -u ${CI_USER} --password-stdin
    - name: Pull from cache (GitHub Package Registry)
      if: github.event_name == 'pull_request' || env.IS_PR_FROM_FORK
      run: docker pull "docker.pkg.github.com/${OWNER}/${DOCKER_CACHE_REPO}/${DOCKER_TAG}"
    - name: Tag docker image
      if: github.event_name == 'pull_request' || env.IS_PR_FROM_FORK
      run: docker tag docker.pkg.github.com/${OWNER}/${DOCKER_CACHE_REPO}/${DOCKER_TAG} ${DOCKER_TAG}
    - name: Export commit range for fork PRs
      if: env.IS_PR_FROM_FORK
      run: |
        echo "PR_COMMIT_RANGE=${{ github.event.client_payload.pull_request.base.sha }}...${{ github.event.client_payload.pull_request.head.sha }}" >> $GITHUB_ENV
    - name: Check pre-commit
      if: github.event_name == 'pull_request' || env.IS_PR_FROM_FORK
      run: |
        docker run \
          -e PR_COMMIT_RANGE \
          -e MJKEY \
          --memory 6500m \
          --memory-swap 6500m \
          "${DOCKER_TAG}" scripts/ci/check_precommit.sh
    - name: Update check status for PRs from forks
      uses: LouisBrunner/checks-action@v1.1.1
      if: env.IS_PR_FROM_FORK && always()
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        name: Check pre-commit
        sha: ${{ github.event.client_payload.pull_request.head.sha }}
        conclusion: ${{ job.status }}


  doctest:
    name: Run Doctest
    runs-on: ubuntu-latest
    needs: check_pre_commit

    steps:
    - name: Login to GitHub Package Registry
      run: echo ${{ secrets.CI_REGISTRY_TOKEN }} | docker login docker.pkg.github.com -u ${CI_USER} --password-stdin
    - name: Pull from cache (GitHub Package Registry)
      run: docker pull "docker.pkg.github.com/${OWNER}/${DOCKER_CACHE_REPO}/${DOCKER_TAG}"
    - name: Tag docker image
      run: docker tag docker.pkg.github.com/${OWNER}/${DOCKER_CACHE_REPO}/${DOCKER_TAG} ${DOCKER_TAG}
    - name: Doctest
      run: |
        docker run \
          -e MJKEY \
          --memory 6500m \
          --memory-swap 6500m \
          "${DOCKER_TAG}" \
          /bin/bash -c \
          'pushd docs && make doctest clean && popd'
    - name: Update check status for PRs from forks
      uses: LouisBrunner/checks-action@v1.1.1
      if: env.IS_PR_FROM_FORK && always()
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        name: Run Doctest
        sha: ${{ github.event.client_payload.pull_request.head.sha }}
        conclusion: ${{ job.status }}


  normal_test:
    name: Normal Tests
    runs-on: ubuntu-latest
    needs: check_pre_commit

    steps:
    - name: Login to GitHub Package Registry
      run: echo ${{ secrets.CI_REGISTRY_TOKEN }} | docker login docker.pkg.github.com -u ${CI_USER} --password-stdin
    - name: Pull from cache (GitHub Package Registry)
      run: docker pull "docker.pkg.github.com/${OWNER}/${DOCKER_CACHE_REPO}/${DOCKER_TAG}"
    - name: Tag docker image
      run: docker tag docker.pkg.github.com/${OWNER}/${DOCKER_CACHE_REPO}/${DOCKER_TAG} ${DOCKER_TAG}
    - name: Normal tests
      run: |
        ci_env="$(bash <(curl -s https://codecov.io/env))" &&
        docker run \
          -e GITHUB_ACTIONS `# used by codecov` \
          -e CODECOV_TOKEN \
          $ci_env\
          --memory 6500m \
          --memory-swap 6500m \
          "${DOCKER_TAG}" \
          /bin/bash -c \
          '[ ! -f ${MJKEY_PATH} ] || mv ${MJKEY_PATH} ${MJKEY_PATH}.bak &&
          pytest --cov=garage --cov-report=xml --reruns 1 -m \
              "not nightly and not huge and not flaky and not large and not mujoco and not mujoco_long" --durations=20 &&
          for i in {1..5}; do
              bash <(curl -s https://codecov.io/bash --retry 5) -Z && break
              if [ $i == 5 ]; then
                  exit 1
              else
                  echo "Retry ${i}..."
                  sleep 30
              fi
          done'
    - name: Update check status for PRs from forks
      uses: LouisBrunner/checks-action@v1.1.1
      if: env.IS_PR_FROM_FORK && always()
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        name: Normal Tests
        sha: ${{ github.event.client_payload.pull_request.head.sha }}
        conclusion: ${{ job.status }}


  large_test:
    name: Large Tests
    runs-on: ubuntu-latest
    needs: check_pre_commit

    steps:
    - name: Login to GitHub Package Registry
      run: echo ${{ secrets.CI_REGISTRY_TOKEN }} | docker login docker.pkg.github.com -u ${CI_USER} --password-stdin
    - name: Pull from cache (GitHub Package Registry)
      run: docker pull "docker.pkg.github.com/${OWNER}/${DOCKER_CACHE_REPO}/${DOCKER_TAG}"
    - name: Tag docker image
      run: docker tag docker.pkg.github.com/${OWNER}/${DOCKER_CACHE_REPO}/${DOCKER_TAG} ${DOCKER_TAG}
    - name: Large tests
      run: |
        ci_env="$(bash <(curl -s https://codecov.io/env))" &&
        docker run \
          -e GITHUB_ACTIONS \
          -e CODECOV_TOKEN \
          $ci_env\
          --memory 6500m \
          --memory-swap 6500m \
          "${DOCKER_TAG}" \
          /bin/bash -c \
          '[ ! -f ${MJKEY_PATH} ] || mv ${MJKEY_PATH} ${MJKEY_PATH}.bak &&
          pytest --cov=garage --cov-report=xml --reruns 1 -m "large and not flaky" --durations=20 &&
          for i in {1..5}; do
              bash <(curl -s https://codecov.io/bash --retry 5) -Z && break
              if [ $i == 5 ]; then
                  exit 1
              else
                  echo "Retry ${i}..."
                  sleep 30
              fi
          done'
    - name: Update check status for PRs from forks
      uses: LouisBrunner/checks-action@v1.1.1
      if: env.IS_PR_FROM_FORK && always()
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        name: Large Tests
        sha: ${{ github.event.client_payload.pull_request.head.sha }}
        conclusion: ${{ job.status }}


  mujoco_test:
    name: MuJoCo-Based Tests
    runs-on: ubuntu-latest
    needs: check_pre_commit

    steps:
    - name: Login to GitHub Package Registry
      run: echo ${{ secrets.CI_REGISTRY_TOKEN }} | docker login docker.pkg.github.com -u ${CI_USER} --password-stdin
    - name: Pull from cache (GitHub Package Registry)
      run: docker pull "docker.pkg.github.com/${OWNER}/${DOCKER_CACHE_REPO}/${DOCKER_TAG}"
    - name: Tag docker image
      run: docker tag docker.pkg.github.com/${OWNER}/${DOCKER_CACHE_REPO}/${DOCKER_TAG} ${DOCKER_TAG}
    - name: MuJoCo tests
      run: |
        ci_env="$(bash <(curl -s https://codecov.io/env))" &&
        docker run \
          -e MJKEY \
          -e GITHUB_ACTIONS \
          -e CODECOV_TOKEN \
          $ci_env\
          --memory 6500m \
          --memory-swap 6500m \
          "${DOCKER_TAG}" \
          /bin/bash -c \
          'pytest --cov=garage --cov-report=xml --reruns 1 -m "mujoco and not flaky" --durations=20 &&
          for i in {1..5}; do
              bash <(curl -s https://codecov.io/bash --retry 5) -Z && break
              if [ $i == 5 ]; then
                  exit 1
              else
                  echo "Retry ${i}..."
                  sleep 30
              fi
          done'
    - name: Update check status for PRs from forks
      uses: LouisBrunner/checks-action@v1.1.1
      if: env.IS_PR_FROM_FORK && always()
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        name: MuJoCo-Based Tests
        sha: ${{ github.event.client_payload.pull_request.head.sha }}
        conclusion: ${{ job.status }}


  mujoco_test_long:
    name: Large MuJoCo-Based Tests
    runs-on: ubuntu-latest
    needs: check_pre_commit

    steps:
    - name: Login to GitHub Package Registry
      run: echo ${{ secrets.CI_REGISTRY_TOKEN }} | docker login docker.pkg.github.com -u ${CI_USER} --password-stdin
    - name: Pull from cache (GitHub Package Registry)
      run: docker pull "docker.pkg.github.com/${OWNER}/${DOCKER_CACHE_REPO}/${DOCKER_TAG}"
    - name: Tag docker image
      run: docker tag docker.pkg.github.com/${OWNER}/${DOCKER_CACHE_REPO}/${DOCKER_TAG} ${DOCKER_TAG}
    - name: Large MuJoCo tests
      run: |
        ci_env="$(bash <(curl -s https://codecov.io/env))" &&
        docker run \
          -e MJKEY \
          -e GITHUB_ACTIONS \
          -e CODECOV_TOKEN \
          $ci_env\
          --memory 6500m \
          --memory-swap 6500m \
          "${DOCKER_TAG}" \
          /bin/bash -c \
          'pytest --cov=garage --cov-report=xml --reruns 1 -m "mujoco_long and not flaky" --durations=20 &&
          for i in {1..5}; do
              bash <(curl -s https://codecov.io/bash --retry 5) -Z && break
              if [ $i == 5 ]; then
                  exit 1
              else
                  echo "Retry ${i}..."
                  sleep 30
              fi
          done'
    - name: Update check status for PRs from forks
      uses: LouisBrunner/checks-action@v1.1.1
      if: env.IS_PR_FROM_FORK && always()
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        name: Large MuJoCo-Based Tests
        sha: ${{ github.event.client_payload.pull_request.head.sha }}
        conclusion: ${{ job.status }}


  deploy_to_pypi:
    name: Deploy to PyPI
    runs-on: ubuntu-latest
    needs: [normal_test, large_test, mujoco_test, mujoco_test_long, doctest]
    if: startsWith(github.ref, 'refs/tags/v')

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Set up Python 3.6
        uses: actions/setup-python@v1
        with:
          python-version: 3.6
      - name: Update Version
        run: echo ${GITHUB_REF##*/} > VERSION
      - name: Setup Distribution
        run: >-
          python setup.py sdist
      - name: Deploy to PyPI
        uses: pypa/gh-action-pypi-publish@master
        with:
          user: __token__
          password: ${{ secrets.PYPI_TOKEN }}


  delete_docker_container:
    name: Delete Docker Container
    runs-on: ubuntu-latest
    needs: [build_docker_container, normal_test, large_test, mujoco_test, mujoco_test_long]
    if: ${{ always() && needs.build_docker_container.result == 'success' }}

    steps:
      - uses: actions/delete-package-versions@v1
        with:
          owner: ${{ env.OWNER }}
          repo: ${{ env.DOCKER_CACHE_REPO }}
          package-name: ${{ env.DOCKER_TAG }}
          token: ${{ secrets.CI_REGISTRY_TOKEN }}
